channels:
  - conda-forge
dependencies:
  - jupyter-server-proxy>=4.3.0
  - jupyterhub-singleuser
  - websockify
  - jupytext
  - nodejs
  - mcstas
  - ncrystal
  - mcpl
  - nexus
  - openmpi
  - nbgitpuller
  - h5py
  - ipympl
  - ipython
  - ipywidgets
  - jupyterlab
  - python-graphviz
  - scipp::plopp
  - scipp::scipp
  - scipy
  - git
  - pip
  - pip:
      - McStasScript
      - guide_bot
      - jupyterquiz
